### ISSUE TITLE
documentation for adding a box for a provider is missing

### ISSUE THREAD

**Issue by johansyd** [hashicorp/atlas-help#11]
Follow the instructions for creating a box that are shown. You'll need to create a box, create a version for that box, then add at least one provider to that box. Follow the forms and they'll guide you through it.

There are no guide for how to set up a provider with a version. A url needs to be added or a box file uploaded, but it should say explicitly that a package.box is needed. 

I tried to follow the https://atlas.hashicorp.com/help/vagrant/boxes/create instructions, but had problems understanding how providers are connected to boxes. The I went to the vagrant documentation and read about providers and read the error messages one more time. It then occurred to me that I needed to connect a new box packaged with a certain provider.

This took me the whole morning to understand.

**Comment by KFishner** [comment]
Thanks for this note. I'm going to write a guide that walks through the box upload process, including the provider step, in much greater detail. Look for an update this week.

**Comment by KFishner** [comment]
Closed with https://atlas.hashicorp.com/help/guides/vagrant-box-create-and-distribute

**Comment by johansyd** [comment]
Thanks. Much more clear now.
