### ISSUE TITLE
The sharing proxy exited with a non-zero exit status! This represents an erroneous exit and likely a bug.

### ISSUE THREAD

**Issue by mans202** [hashicorp/atlas-help#14]
$ vagrant share 2266fb7
==> default: Detecting network information for machine...
    default: Local machine address: 192.168.56.101
    default: Local HTTP port: 80
    default: Local HTTPS port: disabled
==> default: Checking authentication and authorization...
==> default: Creating Vagrant Share session...
    default: Share will be at: tremendous-lynx-6487
The sharing proxy exited with a non-zero exit status! This represents
an erroneous exit and likely a bug. Please report this issue.

**Comment by sethvargo** [comment]
Hi @mans202 

Thank you for reporting this issue. The atlas-help repository if for the help documentation to Atlas. Can you please email support@hashicorp.com with the output of the share command in debug mode?

**Comment by mans202** [comment]
Hi problem solve sorry.
