### ISSUE TITLE
Using Atlas with GitHub: "This feature will roll out in January"

### ISSUE THREAD

**Issue by LouisStAmour** [hashicorp/atlas-help#22]
https://github.com/hashicorp/atlas-help/blob/master/guides/version-control.html.md

Any updates? I'd be particularly interested in a detailed look at how "git push" and "vagrant push" differ as was explained in HN back in Dec.

It'd be nice too if there were endpoints such that either CI systems that commonly integrate with Github are also represented in Atlas for the purpose of hitting a manual "deploy" button when all the checkmarks are green, or as an alternative to this, if Atlas could post to github via hooks or images when things build successfully. I suppose this is where there's fertile cross-over between ops as code and CD systems not just for deploying but for testing as well. I'm coming at this from the perspective of wanting not just Hashicorp tools but also maybe Snap CI-like functionality for manual deploys[1] or integration with SauceLabs' browser testing for sanity checks on a canary deploy. Not that I'm there yet, as currently we're prototyping on a very small system, but I'd like to feel like there's a path forward from tools that could work together to recommended workflows for manual/automated testing and low risk partially-automated deployment strategies. Additionally it'd be fantastic to see a section on immutable server strategies and canary servers or staged deployments using terrafrom with production log feedback and/or NewRelic-style data appearing in Atlas to assist with rollback decisions. And I'm not 100% sure how I can best use Consul, I'll have to dig in to last week's blog post.

*Note: I've yet to fully try and utilize Atlas, so what I've posted so far reflects the state of documentation (perhaps) more than the project's own functionality.*

[1] https://blog.snap-ci.com/blog/2014/07/22/why-snapci-and-travisci-are-not-the-same-thing/

**Comment by KFishner** [comment]
Git integration is still a work in progress

The other features that you're requesting seem to all require an "automatic deploy" from Atlas, which means Atlas running Terraform rather than you running Terraform locally. That's coming in the next month or so. It's a good idea to expose that with an API as well, so you could hypothetically see that your build passes in a CI tool, and then "Atlas Deploy" from there. I've added that as an internal ticket.

Thanks for the feedback!
