### ISSUE TITLE
What is `self-hosted`

### ISSUE THREAD

**Issue by workmaster2n** [hashicorp/atlas-help#30]
When I look at the details of a box, there is always a string that says `self-hosted`. What is that referring to?

**Comment by KFishner** [comment]
Hey there - some people store their Vagrant boxes elsewhere (S3 for example) and just store the metadata on Atlas.

**Comment by workmaster2n** [comment]
Can you point me to an example that is NOT self-hosted? Just out of curiosity

**Comment by KFishner** [comment]
Of course - https://atlas.hashicorp.com/hashicorp/boxes/precise64

**Comment by workmaster2n** [comment]
Those all say self-hosted. Or am I misreading something?

**Comment by KFishner** [comment]
Ah no sorry I sent the wrong link by accident:
https://atlas.hashicorp.com/KFishner/boxes/testbox
