### ISSUE TITLE
document how to upload a box file to atlas from the commandline

### ISSUE THREAD

**Issue by jniggemann** [hashicorp/atlas-help#31]
I've successfully created and tested a box file, that I'd now like to upload to atlas.

The howto I found [https://atlas.hashicorp.com/help/guides/vagrant-box-create-and-distribute](https://atlas.hashicorp.com/help/guides/vagrant-box-create-and-distribute) doesn't mention how I'd upload a box from the commandline (Linux in my case).

**Comment by pearkes** [comment]
I've written a simple guide [here](https://gist.github.com/pearkes/b26b79b772ed34e53fc3) that can be used.

**Comment by sethvargo** [comment]
Hi @jniggemann does that gist help?

**Comment by jniggemann** [comment]
@sethvargo I think so, it looks OK at least - but I didn't try it yet, I'm currently very low on free time...

**Comment by sethvargo** [comment]
Okay cool. I am going to close this, but please report here or email support@hashicorp.com if you get stuck :smile:
